### ISSUE TITLE
Option to keep publishing images even if a calibration file is not specified

### ISSUE THREAD

**Issue by ptrmu** [clydemcqueen/opencv_cam#10]
Maybe there is no calibration because this video file/stream is going to do the calibration. Maybe also an option to publish a default (anything) calibration in-case the consumer requires a camera_info message. (Even if only for getting a system running)

**Comment by ptrmu** [comment]
I see that a camera_info message is published even if one can not be read from a file. An empty camera_info is published in this case. Maybe have options to not publish a camera_info or publish a default camera info with an arbitrary fixed focal length and the center as half the size.

**Comment by clydemcqueen** [comment]
AFAIK images are always published.

I'll look at the CameraInfoManager... this is probably the desired behavior for ROS nodes.

**Comment by ptrmu** [comment]
I was working on a ROS2 node that would calibrate a camera from a series of image messages. Since the camera was being calibrated there was no calibration file containing data for opencv_cam to send in the camera_info message. I worked around the problem by creating a dummy calibration file. But I thought it would be more convenient if opencv_cam had an option to just publish the images without the camera_info messages. Maybe that already exists.

At least this is what I think I meant by this issue.

**Comment by ptrmu** [comment]
You are right. Images are always published even though an error is emitted. This is a non-issue.
