### ISSUE TITLE
intra process communication not working

### ISSUE THREAD

**Issue by christianrauch** [clydemcqueen/opencv_cam#19]
I am trying to get the intra process communication working.

I am just printing the address of published and subscribed messages in the `opencv_cam_node` and `subscriber_node` and I am getting different addresses, e.g.:
```
[opencv_cam]: Image message address [PUBLISH]:      0x7f5574002800
[image_subscriber]: Image message address [SUB]:    0x7f55740018e0
[opencv_cam]: Image message address [PUBLISH]:      0x7f5574002800
[image_subscriber]: Image message address [SUB]:    0x7f55740018e0
[opencv_cam]: Image message address [PUBLISH]:      0x7f5574002800
[image_subscriber]: Image message address [SUB]:    0x7f55740018e0
```

How do I enable the intra process communication such that the messages are shared between both nodes?

**Comment by clydemcqueen** [comment]
Interesting... I'm seeing the same thing on Foxy. Are you running Foxy?

I'll look into this.

**Comment by clydemcqueen** [comment]
Ah, I introduced that bug when I switched to using image_transport in dfc2099b255b8596ec8e28780563347a00a78447. I will back out that change in both branches.

**Comment by clydemcqueen** [comment]
I believe that this is fixed on both branches.
