### ISSUE TITLE
cannot build the opencv_cam files

### ISSUE THREAD

**Issue by nabeeljadoon** [clydemcqueen/opencv_cam#28]
Hello Guys, 
I am using ubuntu 20.04 and ros2-galactic running in virtualbox. I am using logitech C615 camera for calibration etc.

I am trying to build the files as mentioned in readme, but cannot run it. I tried everything. I would appreciate your prompt solution for this. 

Error is here:
**Starting >>> opencv_cam
--- stderr: opencv_cam                               
In file included from /root/opencv_cam_ws/src/opencv_cam/include/opencv_cam/opencv_cam_node.hpp:10,
                 from /root/opencv_cam_ws/src/opencv_cam/src/opencv_cam_node.cpp:1:
/root/opencv_cam_ws/src/opencv_cam/include/opencv_cam/camera_context.hpp:7:10: fatal error: ros2_shared/context_macros.hpp: No such file or directory
    7 | #include "ros2_shared/context_macros.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/opencv_cam_node.dir/build.make:63: CMakeFiles/opencv_cam_node.dir/src/opencv_cam_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/opencv_cam_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2
---
Failed   <<< opencv_cam [13.8s, exited with code 2]

Summary: 1 package finished [19.4s]
  1 package failed: opencv_cam
  1 package had stderr output: opencv_cam**

**Comment by afrye51** [comment]
Fixed in the PR by openvmp here: https://github.com/clydemcqueen/opencv_cam/pull/26

**Comment by clydemcqueen** [comment]
I'll close this, please re-open if it is still a problem.
